# Generated by Django 5.0.1 on 2024-07-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_contact_number', models.CharField(max_length=15)),
                ('dress_type', models.CharField(choices=[('SHIRT', 'Shirt'), ('SUIT', 'Suit')], max_length=5)),
                ('shoulder', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bustline', models.DecimalField(decimal_places=2, max_digits=5)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('round', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height_of_dress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_per_piece', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('advance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comment', models.TextField(blank=True, null=True)),
                ('tailor_name', models.CharField(max_length=255)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('finishing_date', models.DateField()),
                ('sketch_picture', models.ImageField(blank=True, null=True, upload_to='sketches/')),
                ('order_status', models.CharField(choices=[('STARTED', 'Started'), ('PENDING', 'Pending'), ('FINISHED', 'Finished')], default='STARTED', max_length=8)),
            ],
        ),
    ]
